# Generated by Django 3.2.21 on 2023-09-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financenews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
